# Generated by Django 2.1.4 on 2018-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
